"""Add created_at to ai_policies

Revision ID: b5fd4df5a153
Revises: 8637b84240d1
Create Date: 2026-09-05 03:25:58.668141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fd4df5a153'
down_revision: Union[str, None] = '8637b84240d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_policies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_policies', 'created_at')
    # ### end Alembic commands ###
